//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the redhorizon.xml.units package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: redhorizon.xml.units
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLStructureData }
     * 
     */
    public XMLStructureData createXMLStructureData() {
        return new XMLStructureData();
    }

    /**
     * Create an instance of {@link XMLSpecialAnim }
     * 
     */
    public XMLSpecialAnim createXMLSpecialAnim() {
        return new XMLSpecialAnim();
    }

    /**
     * Create an instance of {@link XMLTurretAnimation }
     * 
     */
    public XMLTurretAnimation createXMLTurretAnimation() {
        return new XMLTurretAnimation();
    }

    /**
     * Create an instance of {@link XMLWeaponSlot }
     * 
     */
    public XMLWeaponSlot createXMLWeaponSlot() {
        return new XMLWeaponSlot();
    }

    /**
     * Create an instance of {@link XMLIncludedAnim }
     * 
     */
    public XMLIncludedAnim createXMLIncludedAnim() {
        return new XMLIncludedAnim();
    }

    /**
     * Create an instance of {@link XMLUnitHardpoint }
     * 
     */
    public XMLUnitHardpoint createXMLUnitHardpoint() {
        return new XMLUnitHardpoint();
    }

    /**
     * Create an instance of {@link XMLStructureAnimation }
     * 
     */
    public XMLStructureAnimation createXMLStructureAnimation() {
        return new XMLStructureAnimation();
    }

    /**
     * Create an instance of {@link XMLTurret }
     * 
     */
    public XMLTurret createXMLTurret() {
        return new XMLTurret();
    }

    /**
     * Create an instance of {@link XMLStructure }
     * 
     */
    public XMLStructure createXMLStructure() {
        return new XMLStructure();
    }

    /**
     * Create an instance of {@link XMLVehicle }
     * 
     */
    public XMLVehicle createXMLVehicle() {
        return new XMLVehicle();
    }

    /**
     * Create an instance of {@link XMLInfantry }
     * 
     */
    public XMLInfantry createXMLInfantry() {
        return new XMLInfantry();
    }

    /**
     * Create an instance of {@link XMLStructureDamagedAnimation }
     * 
     */
    public XMLStructureDamagedAnimation createXMLStructureDamagedAnimation() {
        return new XMLStructureDamagedAnimation();
    }

    /**
     * Create an instance of {@link XMLUnitAnimation }
     * 
     */
    public XMLUnitAnimation createXMLUnitAnimation() {
        return new XMLUnitAnimation();
    }

    /**
     * Create an instance of {@link XMLUnitData }
     * 
     */
    public XMLUnitData createXMLUnitData() {
        return new XMLUnitData();
    }

}
