//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncludedAnim complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncludedAnim">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="StartFrame" use="required" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *       &lt;attribute name="Angles" use="required" type="{http://www.ultraq.net.nz/redhorizon/common}positiveInt" />
 *       &lt;attribute name="FramesPerAngle" use="required" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncludedAnim")
@XmlSeeAlso({
    XMLSpecialAnim.class
})
public class XMLIncludedAnim {

    @XmlAttribute(name = "StartFrame", required = true)
    protected int startFrame;
    @XmlAttribute(name = "Angles", required = true)
    protected int angles;
    @XmlAttribute(name = "FramesPerAngle", required = true)
    protected int framesPerAngle;

    /**
     * Gets the value of the startFrame property.
     * 
     */
    public int getStartFrame() {
        return startFrame;
    }

    /**
     * Sets the value of the startFrame property.
     * 
     */
    public void setStartFrame(int value) {
        this.startFrame = value;
    }

    /**
     * Gets the value of the angles property.
     * 
     */
    public int getAngles() {
        return angles;
    }

    /**
     * Sets the value of the angles property.
     * 
     */
    public void setAngles(int value) {
        this.angles = value;
    }

    /**
     * Gets the value of the framesPerAngle property.
     * 
     */
    public int getFramesPerAngle() {
        return framesPerAngle;
    }

    /**
     * Sets the value of the framesPerAngle property.
     * 
     */
    public void setFramesPerAngle(int value) {
        this.framesPerAngle = value;
    }

}
