//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import redhorizon.xml.media.XMLAnimation;


/**
 * <p>Java class for Structure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Structure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/units}Unit">
 *       &lt;sequence>
 *         &lt;element name="Animation" type="{http://www.ultraq.net.nz/redhorizon/units}StructureAnimation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BuildAnimation" type="{http://www.ultraq.net.nz/redhorizon/media}Animation" minOccurs="0"/>
 *         &lt;element name="Turret" type="{http://www.ultraq.net.nz/redhorizon/units}Turret" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="BuildDistance" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="Power" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Storage" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Structure", propOrder = {
    "animation",
    "buildAnimation",
    "turret"
})
public class XMLStructure
    extends XMLUnit
{

    @XmlElement(name = "Animation")
    protected List<XMLStructureAnimation> animation;
    @XmlElement(name = "BuildAnimation")
    protected XMLAnimation buildAnimation;
    @XmlElement(name = "Turret")
    protected List<XMLTurret> turret;
    @XmlAttribute(name = "BuildDistance")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger buildDistance;
    @XmlAttribute(name = "Power")
    protected Integer power;
    @XmlAttribute(name = "Storage")
    protected Integer storage;

    /**
     * Gets the value of the animation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the animation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnimation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLStructureAnimation }
     * 
     * 
     */
    public List<XMLStructureAnimation> getAnimation() {
        if (animation == null) {
            animation = new ArrayList<XMLStructureAnimation>();
        }
        return this.animation;
    }

    /**
     * Gets the value of the buildAnimation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLAnimation }
     *     
     */
    public XMLAnimation getBuildAnimation() {
        return buildAnimation;
    }

    /**
     * Sets the value of the buildAnimation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLAnimation }
     *     
     */
    public void setBuildAnimation(XMLAnimation value) {
        this.buildAnimation = value;
    }

    /**
     * Gets the value of the turret property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the turret property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTurret().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLTurret }
     * 
     * 
     */
    public List<XMLTurret> getTurret() {
        if (turret == null) {
            turret = new ArrayList<XMLTurret>();
        }
        return this.turret;
    }

    /**
     * Gets the value of the buildDistance property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBuildDistance() {
        return buildDistance;
    }

    /**
     * Sets the value of the buildDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBuildDistance(BigInteger value) {
        this.buildDistance = value;
    }

    /**
     * Gets the value of the power property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPower(Integer value) {
        this.power = value;
    }

    /**
     * Gets the value of the storage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStorage() {
        return storage;
    }

    /**
     * Sets the value of the storage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStorage(Integer value) {
        this.storage = value;
    }

}
