//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecialAnim complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecialAnim">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/units}IncludedAnim">
 *       &lt;attribute name="Usage" use="required" type="{http://www.ultraq.net.nz/redhorizon/units}SpecialAnims" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecialAnim")
public class XMLSpecialAnim
    extends XMLIncludedAnim
{

    @XmlAttribute(name = "Usage", required = true)
    protected XMLSpecialAnims usage;

    /**
     * Gets the value of the usage property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSpecialAnims }
     *     
     */
    public XMLSpecialAnims getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSpecialAnims }
     *     
     */
    public void setUsage(XMLSpecialAnims value) {
        this.usage = value;
    }

}
