//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StructureDamagedAnimation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StructureDamagedAnimation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="DefaultAnim" type="{http://www.ultraq.net.nz/redhorizon/units}IncludedAnim"/>
 *         &lt;element name="IncludedAnim" type="{http://www.ultraq.net.nz/redhorizon/units}SpecialAnim" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="StartFrame" use="required" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StructureDamagedAnimation", propOrder = {
    "defaultAnim",
    "includedAnim"
})
public class XMLStructureDamagedAnimation {

    @XmlElement(name = "DefaultAnim")
    protected XMLIncludedAnim defaultAnim;
    @XmlElement(name = "IncludedAnim")
    protected List<XMLSpecialAnim> includedAnim;
    @XmlAttribute(name = "StartFrame", required = true)
    protected int startFrame;

    /**
     * Gets the value of the defaultAnim property.
     * 
     * @return
     *     possible object is
     *     {@link XMLIncludedAnim }
     *     
     */
    public XMLIncludedAnim getDefaultAnim() {
        return defaultAnim;
    }

    /**
     * Sets the value of the defaultAnim property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLIncludedAnim }
     *     
     */
    public void setDefaultAnim(XMLIncludedAnim value) {
        this.defaultAnim = value;
    }

    /**
     * Gets the value of the includedAnim property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includedAnim property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncludedAnim().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLSpecialAnim }
     * 
     * 
     */
    public List<XMLSpecialAnim> getIncludedAnim() {
        if (includedAnim == null) {
            includedAnim = new ArrayList<XMLSpecialAnim>();
        }
        return this.includedAnim;
    }

    /**
     * Gets the value of the startFrame property.
     * 
     */
    public int getStartFrame() {
        return startFrame;
    }

    /**
     * Sets the value of the startFrame property.
     * 
     */
    public void setStartFrame(int value) {
        this.startFrame = value;
    }

}
