//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StructureAnimation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StructureAnimation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/units}UnitAnimation">
 *       &lt;attribute name="DamagedStartFrame" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *       &lt;attribute name="DestroyedFrame" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StructureAnimation")
public class XMLStructureAnimation
    extends XMLUnitAnimation
{

    @XmlAttribute(name = "DamagedStartFrame")
    protected Integer damagedStartFrame;
    @XmlAttribute(name = "DestroyedFrame")
    protected Integer destroyedFrame;

    /**
     * Gets the value of the damagedStartFrame property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDamagedStartFrame() {
        return damagedStartFrame;
    }

    /**
     * Sets the value of the damagedStartFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDamagedStartFrame(Integer value) {
        this.damagedStartFrame = value;
    }

    /**
     * Gets the value of the destroyedFrame property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDestroyedFrame() {
        return destroyedFrame;
    }

    /**
     * Sets the value of the destroyedFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDestroyedFrame(Integer value) {
        this.destroyedFrame = value;
    }

}
