//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import redhorizon.geometry.Point2D;


/**
 * <p>Java class for Turret complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Turret">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Offset" type="{http://www.ultraq.net.nz/redhorizon/common}Point2D"/>
 *         &lt;element name="Hardpoint" type="{http://www.ultraq.net.nz/redhorizon/units}UnitHardpoint" minOccurs="0"/>
 *         &lt;element name="Animation" type="{http://www.ultraq.net.nz/redhorizon/units}TurretAnimation" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RateOfTurn" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Turret", propOrder = {
    "offset",
    "hardpoint",
    "animation"
})
public class XMLTurret {

    @XmlElement(name = "Offset", required = true)
    protected Point2D offset;
    @XmlElement(name = "Hardpoint")
    protected XMLUnitHardpoint hardpoint;
    @XmlElement(name = "Animation")
    protected XMLTurretAnimation animation;
    @XmlAttribute(name = "RateOfTurn")
    protected Integer rateOfTurn;

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Point2D }
     *     
     */
    public Point2D getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Point2D }
     *     
     */
    public void setOffset(Point2D value) {
        this.offset = value;
    }

    /**
     * Gets the value of the hardpoint property.
     * 
     * @return
     *     possible object is
     *     {@link XMLUnitHardpoint }
     *     
     */
    public XMLUnitHardpoint getHardpoint() {
        return hardpoint;
    }

    /**
     * Sets the value of the hardpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLUnitHardpoint }
     *     
     */
    public void setHardpoint(XMLUnitHardpoint value) {
        this.hardpoint = value;
    }

    /**
     * Gets the value of the animation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLTurretAnimation }
     *     
     */
    public XMLTurretAnimation getAnimation() {
        return animation;
    }

    /**
     * Sets the value of the animation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLTurretAnimation }
     *     
     */
    public void setAnimation(XMLTurretAnimation value) {
        this.animation = value;
    }

    /**
     * Gets the value of the rateOfTurn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRateOfTurn() {
        return rateOfTurn;
    }

    /**
     * Sets the value of the rateOfTurn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRateOfTurn(Integer value) {
        this.rateOfTurn = value;
    }

}
