//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import redhorizon.xml.media.XMLAnimation;


/**
 * <p>Java class for TurretAnimation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TurretAnimation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/media}Animation">
 *       &lt;sequence>
 *         &lt;element name="TurretAnim" type="{http://www.ultraq.net.nz/redhorizon/units}IncludedAnim"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TurretAnimation", propOrder = {
    "turretAnim"
})
public class XMLTurretAnimation
    extends XMLAnimation
{

    @XmlElement(name = "TurretAnim", required = true)
    protected XMLIncludedAnim turretAnim;

    /**
     * Gets the value of the turretAnim property.
     * 
     * @return
     *     possible object is
     *     {@link XMLIncludedAnim }
     *     
     */
    public XMLIncludedAnim getTurretAnim() {
        return turretAnim;
    }

    /**
     * Sets the value of the turretAnim property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLIncludedAnim }
     *     
     */
    public void setTurretAnim(XMLIncludedAnim value) {
        this.turretAnim = value;
    }

}
