//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitData element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="UnitData">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="Infantry" type="{http://www.ultraq.net.nz/redhorizon/units}Infantry"/>
 *           &lt;element name="Vehicle" type="{http://www.ultraq.net.nz/redhorizon/units}Vehicle"/>
 *         &lt;/choice>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "infantryOrVehicle"
})
@XmlRootElement(name = "UnitData")
public class XMLUnitData {

    @XmlElements({
        @XmlElement(name = "Vehicle", type = XMLVehicle.class),
        @XmlElement(name = "Infantry", type = XMLInfantry.class)
    })
    protected List<XMLUnit> infantryOrVehicle;

    /**
     * Gets the value of the infantryOrVehicle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infantryOrVehicle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfantryOrVehicle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLVehicle }
     * {@link XMLInfantry }
     * 
     * 
     */
    public List<XMLUnit> getInfantryOrVehicle() {
        if (infantryOrVehicle == null) {
            infantryOrVehicle = new ArrayList<XMLUnit>();
        }
        return this.infantryOrVehicle;
    }

}
