//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import redhorizon.geometry.Point2D;
import redhorizon.xml.XMLReferenceableObject;


/**
 * <p>Java class for UnitHardpoint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnitHardpoint">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/common}ReferenceableObject">
 *       &lt;sequence>
 *         &lt;element name="Offset" type="{http://www.ultraq.net.nz/redhorizon/common}Point2D"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnitHardpoint", propOrder = {
    "offset"
})
public class XMLUnitHardpoint
    extends XMLReferenceableObject
{

    @XmlElement(name = "Offset", required = true)
    protected Point2D offset;

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Point2D }
     *     
     */
    public Point2D getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Point2D }
     *     
     */
    public void setOffset(Point2D value) {
        this.offset = value;
    }

}
