//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import redhorizon.geometry.Area2D;
import redhorizon.xml.XMLExtendableObject;
import redhorizon.xml.media.XMLImage;


/**
 * <p>Java class for Unit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Unit">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/common}ExtendableObject">
 *       &lt;sequence>
 *         &lt;element name="Footprint" type="{http://www.ultraq.net.nz/redhorizon/common}Area2D" minOccurs="0"/>
 *         &lt;element name="Hardpoint" type="{http://www.ultraq.net.nz/redhorizon/units}UnitHardpoint" minOccurs="0"/>
 *         &lt;element name="WeaponSlot" type="{http://www.ultraq.net.nz/redhorizon/units}WeaponSlot" minOccurs="0"/>
 *         &lt;element name="Portrait" type="{http://www.ultraq.net.nz/redhorizon/media}Image" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Armour" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Cost" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *       &lt;attribute name="Hitpoints" type="{http://www.ultraq.net.nz/redhorizon/common}positiveInt" />
 *       &lt;attribute name="Points" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *       &lt;attribute name="Prerequisites">
 *         &lt;simpleType>
 *           &lt;list itemType="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="RateOfTurn" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *       &lt;attribute name="Sight" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *       &lt;attribute name="Speed" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *       &lt;attribute name="TechLevel" type="{http://www.ultraq.net.nz/redhorizon/common}negativeOnePlusInt" />
 *       &lt;attribute name="Characteristics">
 *         &lt;simpleType>
 *           &lt;list itemType="{http://www.ultraq.net.nz/redhorizon/units}UnitCharacteristics" />
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="UnCharacteristics">
 *         &lt;simpleType>
 *           &lt;list itemType="{http://www.ultraq.net.nz/redhorizon/units}UnitCharacteristics" />
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Unit", propOrder = {
    "footprint",
    "hardpoint",
    "weaponSlot",
    "portrait"
})
@XmlSeeAlso({
    XMLInfantry.class,
    XMLStructure.class,
    XMLVehicle.class
})
public abstract class XMLUnit
    extends XMLExtendableObject
{

    @XmlElement(name = "Footprint")
    protected Area2D footprint;
    @XmlElement(name = "Hardpoint")
    protected XMLUnitHardpoint hardpoint;
    @XmlElement(name = "WeaponSlot")
    protected XMLWeaponSlot weaponSlot;
    @XmlElement(name = "Portrait")
    protected XMLImage portrait;
    @XmlAttribute(name = "Armour")
    protected String armour;
    @XmlAttribute(name = "Cost")
    protected Integer cost;
    @XmlAttribute(name = "Hitpoints")
    protected Integer hitpoints;
    @XmlAttribute(name = "Points")
    protected Integer points;
    @XmlAttribute(name = "Prerequisites")
    protected List<String> prerequisites;
    @XmlAttribute(name = "RateOfTurn")
    protected Integer rateOfTurn;
    @XmlAttribute(name = "Sight")
    protected Integer sight;
    @XmlAttribute(name = "Speed")
    protected Integer speed;
    @XmlAttribute(name = "TechLevel")
    protected Integer techLevel;
    @XmlAttribute(name = "Characteristics")
    protected List<XMLUnitCharacteristics> characteristics;
    @XmlAttribute(name = "UnCharacteristics")
    protected List<XMLUnitCharacteristics> unCharacteristics;

    /**
     * Gets the value of the footprint property.
     * 
     * @return
     *     possible object is
     *     {@link Area2D }
     *     
     */
    public Area2D getFootprint() {
        return footprint;
    }

    /**
     * Sets the value of the footprint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area2D }
     *     
     */
    public void setFootprint(Area2D value) {
        this.footprint = value;
    }

    public boolean isSetFootprint() {
        return (this.footprint!= null);
    }

    /**
     * Gets the value of the hardpoint property.
     * 
     * @return
     *     possible object is
     *     {@link XMLUnitHardpoint }
     *     
     */
    public XMLUnitHardpoint getHardpoint() {
        return hardpoint;
    }

    /**
     * Sets the value of the hardpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLUnitHardpoint }
     *     
     */
    public void setHardpoint(XMLUnitHardpoint value) {
        this.hardpoint = value;
    }

    /**
     * Gets the value of the weaponSlot property.
     * 
     * @return
     *     possible object is
     *     {@link XMLWeaponSlot }
     *     
     */
    public XMLWeaponSlot getWeaponSlot() {
        return weaponSlot;
    }

    /**
     * Sets the value of the weaponSlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLWeaponSlot }
     *     
     */
    public void setWeaponSlot(XMLWeaponSlot value) {
        this.weaponSlot = value;
    }

    /**
     * Gets the value of the portrait property.
     * 
     * @return
     *     possible object is
     *     {@link XMLImage }
     *     
     */
    public XMLImage getPortrait() {
        return portrait;
    }

    /**
     * Sets the value of the portrait property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLImage }
     *     
     */
    public void setPortrait(XMLImage value) {
        this.portrait = value;
    }

    /**
     * Gets the value of the armour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArmour() {
        return armour;
    }

    /**
     * Sets the value of the armour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArmour(String value) {
        this.armour = value;
    }

    /**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCost(Integer value) {
        this.cost = value;
    }

    /**
     * Gets the value of the hitpoints property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHitpoints() {
        return hitpoints;
    }

    /**
     * Sets the value of the hitpoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHitpoints(Integer value) {
        this.hitpoints = value;
    }

    /**
     * Gets the value of the points property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * Sets the value of the points property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPoints(Integer value) {
        this.points = value;
    }

    /**
     * Gets the value of the prerequisites property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prerequisites property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrerequisites().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPrerequisites() {
        if (prerequisites == null) {
            prerequisites = new ArrayList<String>();
        }
        return this.prerequisites;
    }

    /**
     * Gets the value of the rateOfTurn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRateOfTurn() {
        return rateOfTurn;
    }

    /**
     * Sets the value of the rateOfTurn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRateOfTurn(Integer value) {
        this.rateOfTurn = value;
    }

    /**
     * Gets the value of the sight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSight() {
        return sight;
    }

    /**
     * Sets the value of the sight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSight(Integer value) {
        this.sight = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSpeed(Integer value) {
        this.speed = value;
    }

    /**
     * Gets the value of the techLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTechLevel() {
        return techLevel;
    }

    /**
     * Sets the value of the techLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTechLevel(Integer value) {
        this.techLevel = value;
    }

    /**
     * Gets the value of the characteristics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the characteristics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharacteristics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLUnitCharacteristics }
     * 
     * 
     */
    public List<XMLUnitCharacteristics> getCharacteristics() {
        if (characteristics == null) {
            characteristics = new ArrayList<XMLUnitCharacteristics>();
        }
        return this.characteristics;
    }

    /**
     * Gets the value of the unCharacteristics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unCharacteristics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnCharacteristics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLUnitCharacteristics }
     * 
     * 
     */
    public List<XMLUnitCharacteristics> getUnCharacteristics() {
        if (unCharacteristics == null) {
            unCharacteristics = new ArrayList<XMLUnitCharacteristics>();
        }
        return this.unCharacteristics;
    }

}
