//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitCharacteristics.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnitCharacteristics">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BIB"/>
 *     &lt;enumeration value="BUILD_ADJACENT"/>
 *     &lt;enumeration value="CAPTURABLE"/>
 *     &lt;enumeration value="CREWED"/>
 *     &lt;enumeration value="POWERED"/>
 *     &lt;enumeration value="REPAIRABLE"/>
 *     &lt;enumeration value="SELF_HEALING"/>
 *     &lt;enumeration value="SENSORS"/>
 *     &lt;enumeration value="TRACKED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UnitCharacteristics")
@XmlEnum
public enum XMLUnitCharacteristics {

    BIB,
    BUILD_ADJACENT,
    CAPTURABLE,
    CREWED,
    POWERED,
    REPAIRABLE,
    SELF_HEALING,
    SENSORS,
    TRACKED;

    public String value() {
        return name();
    }

    public static XMLUnitCharacteristics fromValue(String v) {
        return valueOf(v);
    }

}
