//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Vehicle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Vehicle">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/units}Unit">
 *       &lt;sequence>
 *         &lt;element name="Animation" type="{http://www.ultraq.net.nz/redhorizon/units}UnitAnimation" minOccurs="0"/>
 *         &lt;element name="Turret" type="{http://www.ultraq.net.nz/redhorizon/units}Turret" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Vehicle", propOrder = {
    "animation",
    "turret"
})
public class XMLVehicle
    extends XMLUnit
{

    @XmlElement(name = "Animation")
    protected XMLUnitAnimation animation;
    @XmlElement(name = "Turret")
    protected List<XMLTurret> turret;

    /**
     * Gets the value of the animation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLUnitAnimation }
     *     
     */
    public XMLUnitAnimation getAnimation() {
        return animation;
    }

    /**
     * Sets the value of the animation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLUnitAnimation }
     *     
     */
    public void setAnimation(XMLUnitAnimation value) {
        this.animation = value;
    }

    /**
     * Gets the value of the turret property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the turret property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTurret().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLTurret }
     * 
     * 
     */
    public List<XMLTurret> getTurret() {
        if (turret == null) {
            turret = new ArrayList<XMLTurret>();
        }
        return this.turret;
    }

}
