//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.units;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import redhorizon.xml.weapons.XMLWeapon;


/**
 * <p>Java class for WeaponSlot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WeaponSlot">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Weapon" type="{http://www.ultraq.net.nz/redhorizon/weapons}Weapon"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AmmoCapacity" type="{http://www.ultraq.net.nz/redhorizon/common}negativeOnePlusInt" default="-1" />
 *       &lt;attribute name="ReloadRate" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" default="0" />
 *       &lt;attribute name="HardpointsUsed">
 *         &lt;simpleType>
 *           &lt;list itemType="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Characteristics">
 *         &lt;simpleType>
 *           &lt;list itemType="{http://www.ultraq.net.nz/redhorizon/units}WeaponCharacteristics" />
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="UnCharacteristics">
 *         &lt;simpleType>
 *           &lt;list itemType="{http://www.ultraq.net.nz/redhorizon/units}WeaponCharacteristics" />
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeaponSlot", propOrder = {
    "weapon"
})
public class XMLWeaponSlot {

    @XmlElement(name = "Weapon", required = true)
    protected XMLWeapon weapon;
    @XmlAttribute(name = "AmmoCapacity")
    protected Integer ammoCapacity;
    @XmlAttribute(name = "ReloadRate")
    protected Integer reloadRate;
    @XmlAttribute(name = "HardpointsUsed")
    protected List<String> hardpointsUsed;
    @XmlAttribute(name = "Characteristics")
    protected List<XMLWeaponCharacteristics> characteristics;
    @XmlAttribute(name = "UnCharacteristics")
    protected List<XMLWeaponCharacteristics> unCharacteristics;

    /**
     * Gets the value of the weapon property.
     * 
     * @return
     *     possible object is
     *     {@link XMLWeapon }
     *     
     */
    public XMLWeapon getWeapon() {
        return weapon;
    }

    /**
     * Sets the value of the weapon property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLWeapon }
     *     
     */
    public void setWeapon(XMLWeapon value) {
        this.weapon = value;
    }

    /**
     * Gets the value of the ammoCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getAmmoCapacity() {
        if (ammoCapacity == null) {
            return -1;
        } else {
            return ammoCapacity;
        }
    }

    /**
     * Sets the value of the ammoCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAmmoCapacity(Integer value) {
        this.ammoCapacity = value;
    }

    /**
     * Gets the value of the reloadRate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getReloadRate() {
        if (reloadRate == null) {
            return  0;
        } else {
            return reloadRate;
        }
    }

    /**
     * Sets the value of the reloadRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReloadRate(Integer value) {
        this.reloadRate = value;
    }

    /**
     * Gets the value of the hardpointsUsed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hardpointsUsed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHardpointsUsed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHardpointsUsed() {
        if (hardpointsUsed == null) {
            hardpointsUsed = new ArrayList<String>();
        }
        return this.hardpointsUsed;
    }

    /**
     * Gets the value of the characteristics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the characteristics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharacteristics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLWeaponCharacteristics }
     * 
     * 
     */
    public List<XMLWeaponCharacteristics> getCharacteristics() {
        if (characteristics == null) {
            characteristics = new ArrayList<XMLWeaponCharacteristics>();
        }
        return this.characteristics;
    }

    /**
     * Gets the value of the unCharacteristics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unCharacteristics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnCharacteristics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLWeaponCharacteristics }
     * 
     * 
     */
    public List<XMLWeaponCharacteristics> getUnCharacteristics() {
        if (unCharacteristics == null) {
            unCharacteristics = new ArrayList<XMLWeaponCharacteristics>();
        }
        return this.unCharacteristics;
    }

}
