
// ==================================
// Scanner's Java - Game strings keys
// ==================================

package redhorizon.game.mission;

import redhorizon.strings.StringsKey;

/**
 * Enumeration of keys to strings used for the missions of Red Alert and
 * Tiberium Dawn.
 * 
 * @author Emanuel Rabina
 */
public enum CNCMissionsStringsKeys implements StringsKey {

	// Generic campaign names
	GAMENEW_NEWGAME,

	// Red Alert campaign names
	CAMPAIGN_RA_ALLIES,    CAMPAIGN_RA_SOVIET,
	DESCRIPTION_RA_ALLIES, DESCRIPTION_RA_SOVIET,

	// Tiberium Dawn campaign names
	CAMPAIGN_TD_GDI,    CAMPAIGN_TD_NOD,
	DESCRIPTION_TD_GDI, DESCRIPTION_TD_NOD,

	// RA - Allied mission names
	MISSION_RA_ALLIES_01ea,
	MISSION_RA_ALLIES_02ea,
	MISSION_RA_ALLIES_03ea, MISSION_RA_ALLIES_03eb,
	MISSION_RA_ALLIES_04ea,
	MISSION_RA_ALLIES_05ea, MISSION_RA_ALLIES_05eb, MISSION_RA_ALLIES_05ec,
	MISSION_RA_ALLIES_06ea, MISSION_RA_ALLIES_06eb,
	MISSION_RA_ALLIES_07ea,
	MISSION_RA_ALLIES_08ea, MISSION_RA_ALLIES_08eb,
	MISSION_RA_ALLIES_09ea, MISSION_RA_ALLIES_09eb,
	MISSION_RA_ALLIES_10ea, MISSION_RA_ALLIES_10eb,
	MISSION_RA_ALLIES_11ea, MISSION_RA_ALLIES_11eb,
	MISSION_RA_ALLIES_12ea,
	MISSION_RA_ALLIES_13ea,
	MISSION_RA_ALLIES_14ea,

	// Soviet mission names
	MISSION_RA_SOVIET_01ea,
	MISSION_RA_SOVIET_02ea, MISSION_RA_SOVIET_02eb,
	MISSION_RA_SOVIET_03ea,
	MISSION_RA_SOVIET_04ea, MISSION_RA_SOVIET_04eb,
	MISSION_RA_SOVIET_05ea,
	MISSION_RA_SOVIET_06ea, MISSION_RA_SOVIET_06eb,
	MISSION_RA_SOVIET_07ea,
	MISSION_RA_SOVIET_08ea, MISSION_RA_SOVIET_08eb,
	MISSION_RA_SOVIET_09ea,
	MISSION_RA_SOVIET_10ea,
	MISSION_RA_SOVIET_11ea, MISSION_RA_SOVIET_11eb,
	MISSION_RA_SOVIET_12ea,
	MISSION_RA_SOVIET_13ea, MISSION_RA_SOVIET_13eb,
	MISSION_RA_SOVIET_14ea,

	// GDI mission names
	MISSION_TD_GDI_01ea,
	MISSION_TD_GDI_02ea,
	MISSION_TD_GDI_03ea,
	MISSION_TD_GDI_04ea, MISSION_TD_GDI_04wa, MISSION_TD_GDI_04wb,
	MISSION_TD_GDI_05ea, MISSION_TD_GDI_05wa, MISSION_TD_GDI_05wb,
	MISSION_TD_GDI_07ea,
	MISSION_TD_GDI_08ea, MISSION_TD_GDI_08eb,
	MISSION_TD_GDI_09ea,
	MISSION_TD_GDI_10ea, MISSION_TD_GDI_10eb,
	MISSION_TD_GDI_11ea,
	MISSION_TD_GDI_12ea, MISSION_TD_GDI_12eb,
	MISSION_TD_GDI_13ea,
	MISSION_TD_GDI_14ea,
	MISSION_TD_GDI_15ea, MISSION_TD_GDI_15eb, MISSION_TD_GDI_15ec,

	// Nod mission names
	MISSION_TD_NOD_01ea,
	MISSION_TD_NOD_02ea, MISSION_TD_NOD_02eb,
	MISSION_TD_NOD_03ea, MISSION_TD_NOD_03eb,
	MISSION_TD_NOD_04ea, MISSION_TD_NOD_04eb,
	MISSION_TD_NOD_05ea,
	MISSION_TD_NOD_06ea, MISSION_TD_NOD_06eb, MISSION_TD_NOD_06ec,
	MISSION_TD_NOD_07ea, MISSION_TD_NOD_07eb, MISSION_TD_NOD_07ec,
	MISSION_TD_NOD_08ea, MISSION_TD_NOD_08eb,
	MISSION_TD_NOD_09ea,
	MISSION_TD_NOD_10ea, MISSION_TD_NOD_10eb,
	MISSION_TD_NOD_11ea, MISSION_TD_NOD_11eb,
	MISSION_TD_NOD_12ea,
	MISSION_TD_NOD_13ea, MISSION_TD_NOD_13eb, MISSION_TD_NOD_13ec,

	// RA - Allied briefings
	BRIEFING_RA_ALLIES_01ea,
	BRIEFING_RA_ALLIES_02ea,
	BRIEFING_RA_ALLIES_03ea, BRIEFING_RA_ALLIES_03eb,
	BRIEFING_RA_ALLIES_04ea,
	BRIEFING_RA_ALLIES_05ea, BRIEFING_RA_ALLIES_05eb, BRIEFING_RA_ALLIES_05ec,
	BRIEFING_RA_ALLIES_06ea, BRIEFING_RA_ALLIES_06eb,
	BRIEFING_RA_ALLIES_07ea,
	BRIEFING_RA_ALLIES_08ea, BRIEFING_RA_ALLIES_08eb,
	BRIEFING_RA_ALLIES_09ea, BRIEFING_RA_ALLIES_09eb,
	BRIEFING_RA_ALLIES_10ea, BRIEFING_RA_ALLIES_10eb,
	BRIEFING_RA_ALLIES_11ea, BRIEFING_RA_ALLIES_11eb,
	BRIEFING_RA_ALLIES_12ea,
	BRIEFING_RA_ALLIES_13ea,
	BRIEFING_RA_ALLIES_14ea,

	// RA - Soviet briefings
	BRIEFING_RA_SOVIET_01ea,
	BRIEFING_RA_SOVIET_02ea, BRIEFING_RA_SOVIET_02eb,
	BRIEFING_RA_SOVIET_03ea,
	BRIEFING_RA_SOVIET_04ea, BRIEFING_RA_SOVIET_04eb,
	BRIEFING_RA_SOVIET_05ea,
	BRIEFING_RA_SOVIET_06ea, BRIEFING_RA_SOVIET_06eb,
	BRIEFING_RA_SOVIET_07ea,
	BRIEFING_RA_SOVIET_08ea, BRIEFING_RA_SOVIET_08eb,
	BRIEFING_RA_SOVIET_09ea,
	BRIEFING_RA_SOVIET_10ea,
	BRIEFING_RA_SOVIET_11ea, BRIEFING_RA_SOVIET_11eb,
	BRIEFING_RA_SOVIET_12ea,
	BRIEFING_RA_SOVIET_13ea, BRIEFING_RA_SOVIET_13eb,
	BRIEFING_RA_SOVIET_14ea,

	// TD - GDI briefings
	BRIEFING_TD_GDI_01ea,
	BRIEFING_TD_GDI_02ea,
	BRIEFING_TD_GDI_03ea,
	BRIEFING_TD_GDI_04ea, BRIEFING_TD_GDI_04wa, BRIEFING_TD_GDI_04wb,
	BRIEFING_TD_GDI_05ea, BRIEFING_TD_GDI_05wa, BRIEFING_TD_GDI_05wb,
	BRIEFING_TD_GDI_07ea,
	BRIEFING_TD_GDI_08ea, BRIEFING_TD_GDI_08eb,
	BRIEFING_TD_GDI_09ea,
	BRIEFING_TD_GDI_10ea, BRIEFING_TD_GDI_10eb,
	BRIEFING_TD_GDI_11ea,
	BRIEFING_TD_GDI_12ea, BRIEFING_TD_GDI_12eb,
	BRIEFING_TD_GDI_13ea,
	BRIEFING_TD_GDI_14ea,
	BRIEFING_TD_GDI_15ea, BRIEFING_TD_GDI_15eb, BRIEFING_TD_GDI_15ec,

	// TD - Nod briefings
	BRIEFING_TD_NOD_01ea,
	BRIEFING_TD_NOD_02ea, BRIEFING_TD_NOD_02eb,
	BRIEFING_TD_NOD_03ea, BRIEFING_TD_NOD_03eb,
	BRIEFING_TD_NOD_04ea, BRIEFING_TD_NOD_04eb,
	BRIEFING_TD_NOD_05ea,
	BRIEFING_TD_NOD_06ea, BRIEFING_TD_NOD_06eb, BRIEFING_TD_NOD_06ec,
	BRIEFING_TD_NOD_07ea, BRIEFING_TD_NOD_07eb, BRIEFING_TD_NOD_07ec,
	BRIEFING_TD_NOD_08ea, BRIEFING_TD_NOD_08eb,
	BRIEFING_TD_NOD_09ea,
	BRIEFING_TD_NOD_10ea, BRIEFING_TD_NOD_10eb,
	BRIEFING_TD_NOD_11ea, BRIEFING_TD_NOD_11eb,
	BRIEFING_TD_NOD_12ea,
	BRIEFING_TD_NOD_13ea, BRIEFING_TD_NOD_13eb, BRIEFING_TD_NOD_13ec;

	private static final String RESOURCEBUNDLE_MISSIONS = "Game_Missions";

	/**
	 * @inheritDoc
	 */
	public String getKey() {

		return name();
	}

	/**
	 * @inheritDoc
	 */
	public String getResourceBundle() {

		return RESOURCEBUNDLE_MISSIONS;
	}
}
