//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.campaign;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the redhorizon.xml.campaign package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: redhorizon.xml.campaign
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLCampaignData }
     * 
     */
    public XMLCampaignData createXMLCampaignData() {
        return new XMLCampaignData();
    }

    /**
     * Create an instance of {@link XMLEndingRef }
     * 
     */
    public XMLEndingRef createXMLEndingRef() {
        return new XMLEndingRef();
    }

    /**
     * Create an instance of {@link XMLMissionRef }
     * 
     */
    public XMLMissionRef createXMLMissionRef() {
        return new XMLMissionRef();
    }

    /**
     * Create an instance of {@link XMLName }
     * 
     */
    public XMLName createXMLName() {
        return new XMLName();
    }

    /**
     * Create an instance of {@link XMLMissionNode }
     * 
     */
    public XMLMissionNode createXMLMissionNode() {
        return new XMLMissionNode();
    }

    /**
     * Create an instance of {@link XMLCampaign }
     * 
     */
    public XMLCampaign createXMLCampaign() {
        return new XMLCampaign();
    }

    /**
     * Create an instance of {@link XMLEnding }
     * 
     */
    public XMLEnding createXMLEnding() {
        return new XMLEnding();
    }

    /**
     * Create an instance of {@link XMLMission }
     * 
     */
    public XMLMission createXMLMission() {
        return new XMLMission();
    }

    /**
     * Create an instance of {@link XMLMissionNodeRef }
     * 
     */
    public XMLMissionNodeRef createXMLMissionNodeRef() {
        return new XMLMissionNodeRef();
    }

    /**
     * Create an instance of {@link XMLDescription }
     * 
     */
    public XMLDescription createXMLDescription() {
        return new XMLDescription();
    }

    /**
     * Create an instance of {@link XMLMissionTree }
     * 
     */
    public XMLMissionTree createXMLMissionTree() {
        return new XMLMissionTree();
    }

}
