//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.rules;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import redhorizon.xml.XMLIncludes;


/**
 * <p>Java class for Rules element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="Rules">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="Soundtrack" type="{http://www.ultraq.net.nz/redhorizon/common}XMLIncludes"/>
 *           &lt;element name="Factions" type="{http://www.ultraq.net.nz/redhorizon/common}XMLIncludes"/>
 *           &lt;element name="Units" type="{http://www.ultraq.net.nz/redhorizon/common}XMLIncludes"/>
 *           &lt;element name="Structures" type="{http://www.ultraq.net.nz/redhorizon/common}XMLIncludes"/>
 *           &lt;element name="Weapons" type="{http://www.ultraq.net.nz/redhorizon/common}XMLIncludes"/>
 *           &lt;element name="Projectiles" type="{http://www.ultraq.net.nz/redhorizon/common}XMLIncludes"/>
 *           &lt;element name="Warheads" type="{http://www.ultraq.net.nz/redhorizon/common}XMLIncludes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "soundtrack",
    "factions",
    "units",
    "structures",
    "weapons",
    "projectiles",
    "warheads"
})
@XmlRootElement(name = "Rules")
public class XMLRules {

    @XmlElement(name = "Soundtrack", required = true)
    protected XMLIncludes soundtrack;
    @XmlElement(name = "Factions", required = true)
    protected XMLIncludes factions;
    @XmlElement(name = "Units", required = true)
    protected XMLIncludes units;
    @XmlElement(name = "Structures", required = true)
    protected XMLIncludes structures;
    @XmlElement(name = "Weapons", required = true)
    protected XMLIncludes weapons;
    @XmlElement(name = "Projectiles", required = true)
    protected XMLIncludes projectiles;
    @XmlElement(name = "Warheads", required = true)
    protected XMLIncludes warheads;

    /**
     * Gets the value of the soundtrack property.
     * 
     * @return
     *     possible object is
     *     {@link XMLIncludes }
     *     
     */
    public XMLIncludes getSoundtrack() {
        return soundtrack;
    }

    /**
     * Sets the value of the soundtrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLIncludes }
     *     
     */
    public void setSoundtrack(XMLIncludes value) {
        this.soundtrack = value;
    }

    /**
     * Gets the value of the factions property.
     * 
     * @return
     *     possible object is
     *     {@link XMLIncludes }
     *     
     */
    public XMLIncludes getFactions() {
        return factions;
    }

    /**
     * Sets the value of the factions property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLIncludes }
     *     
     */
    public void setFactions(XMLIncludes value) {
        this.factions = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link XMLIncludes }
     *     
     */
    public XMLIncludes getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLIncludes }
     *     
     */
    public void setUnits(XMLIncludes value) {
        this.units = value;
    }

    /**
     * Gets the value of the structures property.
     * 
     * @return
     *     possible object is
     *     {@link XMLIncludes }
     *     
     */
    public XMLIncludes getStructures() {
        return structures;
    }

    /**
     * Sets the value of the structures property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLIncludes }
     *     
     */
    public void setStructures(XMLIncludes value) {
        this.structures = value;
    }

    /**
     * Gets the value of the weapons property.
     * 
     * @return
     *     possible object is
     *     {@link XMLIncludes }
     *     
     */
    public XMLIncludes getWeapons() {
        return weapons;
    }

    /**
     * Sets the value of the weapons property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLIncludes }
     *     
     */
    public void setWeapons(XMLIncludes value) {
        this.weapons = value;
    }

    /**
     * Gets the value of the projectiles property.
     * 
     * @return
     *     possible object is
     *     {@link XMLIncludes }
     *     
     */
    public XMLIncludes getProjectiles() {
        return projectiles;
    }

    /**
     * Sets the value of the projectiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLIncludes }
     *     
     */
    public void setProjectiles(XMLIncludes value) {
        this.projectiles = value;
    }

    /**
     * Gets the value of the warheads property.
     * 
     * @return
     *     possible object is
     *     {@link XMLIncludes }
     *     
     */
    public XMLIncludes getWarheads() {
        return warheads;
    }

    /**
     * Sets the value of the warheads property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLIncludes }
     *     
     */
    public void setWarheads(XMLIncludes value) {
        this.warheads = value;
    }

}
