//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.weapons;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import redhorizon.xml.media.XMLAnimation;


/**
 * <p>Java class for FiringAnimation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FiringAnimation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/media}Animation">
 *       &lt;attribute name="Angles" use="required" type="{http://www.ultraq.net.nz/redhorizon/common}positiveInt" />
 *       &lt;attribute name="FramesPerAngle" type="{http://www.ultraq.net.nz/redhorizon/common}positiveInt" default="1" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FiringAnimation")
public class XMLFiringAnimation
    extends XMLAnimation
{

    @XmlAttribute(name = "Angles", required = true)
    protected int angles;
    @XmlAttribute(name = "FramesPerAngle")
    protected Integer framesPerAngle;

    /**
     * Gets the value of the angles property.
     * 
     */
    public int getAngles() {
        return angles;
    }

    /**
     * Sets the value of the angles property.
     * 
     */
    public void setAngles(int value) {
        this.angles = value;
    }

    /**
     * Gets the value of the framesPerAngle property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getFramesPerAngle() {
        if (framesPerAngle == null) {
            return  1;
        } else {
            return framesPerAngle;
        }
    }

    /**
     * Sets the value of the framesPerAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFramesPerAngle(Integer value) {
        this.framesPerAngle = value;
    }

}
