//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.weapons;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import redhorizon.xml.XMLExtendableObject;
import redhorizon.xml.media.XMLSoundEffect;
import redhorizon.xml.projectiles.XMLProjectile;
import redhorizon.xml.warheads.XMLWarhead;


/**
 * <p>Java class for Weapon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Weapon">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/common}ExtendableObject">
 *       &lt;sequence>
 *         &lt;element name="Animation" type="{http://www.ultraq.net.nz/redhorizon/weapons}FiringAnimation" minOccurs="0"/>
 *         &lt;element name="Projectile" type="{http://www.ultraq.net.nz/redhorizon/projectiles}Projectile" minOccurs="0"/>
 *         &lt;element name="SoundEffect" type="{http://www.ultraq.net.nz/redhorizon/media}SoundEffect" minOccurs="0"/>
 *         &lt;element name="Warhead" type="{http://www.ultraq.net.nz/redhorizon/warheads}Warhead" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Damage" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Range" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *       &lt;attribute name="RateOfFire" type="{http://www.ultraq.net.nz/redhorizon/common}positiveInt" />
 *       &lt;attribute name="Speed" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Weapon", propOrder = {
    "animation",
    "projectile",
    "soundEffect",
    "warhead"
})
public class XMLWeapon
    extends XMLExtendableObject
{

    @XmlElement(name = "Animation")
    protected XMLFiringAnimation animation;
    @XmlElement(name = "Projectile")
    protected XMLProjectile projectile;
    @XmlElement(name = "SoundEffect")
    protected XMLSoundEffect soundEffect;
    @XmlElement(name = "Warhead")
    protected XMLWarhead warhead;
    @XmlAttribute(name = "Damage")
    protected BigInteger damage;
    @XmlAttribute(name = "Range")
    protected Integer range;
    @XmlAttribute(name = "RateOfFire")
    protected Integer rateOfFire;
    @XmlAttribute(name = "Speed")
    protected Integer speed;

    /**
     * Gets the value of the animation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLFiringAnimation }
     *     
     */
    public XMLFiringAnimation getAnimation() {
        return animation;
    }

    /**
     * Sets the value of the animation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLFiringAnimation }
     *     
     */
    public void setAnimation(XMLFiringAnimation value) {
        this.animation = value;
    }

    /**
     * Gets the value of the projectile property.
     * 
     * @return
     *     possible object is
     *     {@link XMLProjectile }
     *     
     */
    public XMLProjectile getProjectile() {
        return projectile;
    }

    /**
     * Sets the value of the projectile property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLProjectile }
     *     
     */
    public void setProjectile(XMLProjectile value) {
        this.projectile = value;
    }

    /**
     * Gets the value of the soundEffect property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSoundEffect }
     *     
     */
    public XMLSoundEffect getSoundEffect() {
        return soundEffect;
    }

    /**
     * Sets the value of the soundEffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSoundEffect }
     *     
     */
    public void setSoundEffect(XMLSoundEffect value) {
        this.soundEffect = value;
    }

    /**
     * Gets the value of the warhead property.
     * 
     * @return
     *     possible object is
     *     {@link XMLWarhead }
     *     
     */
    public XMLWarhead getWarhead() {
        return warhead;
    }

    /**
     * Sets the value of the warhead property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLWarhead }
     *     
     */
    public void setWarhead(XMLWarhead value) {
        this.warhead = value;
    }

    /**
     * Gets the value of the damage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDamage() {
        return damage;
    }

    /**
     * Sets the value of the damage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDamage(BigInteger value) {
        this.damage = value;
    }

    /**
     * Gets the value of the range property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRange(Integer value) {
        this.range = value;
    }

    /**
     * Gets the value of the rateOfFire property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRateOfFire() {
        return rateOfFire;
    }

    /**
     * Sets the value of the rateOfFire property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRateOfFire(Integer value) {
        this.rateOfFire = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSpeed(Integer value) {
        this.speed = value;
    }

}
