//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.soundtrack;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import redhorizon.xml.media.XMLSoundTrack;


/**
 * <p>Java class for SoundtrackData element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="SoundtrackData">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence maxOccurs="unbounded">
 *           &lt;element name="Soundtrack" type="{http://www.ultraq.net.nz/redhorizon/media}Soundtrack"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "soundtrack"
})
@XmlRootElement(name = "SoundtrackData")
public class XMLSoundtrackData {

    @XmlElement(name = "Soundtrack", required = true)
    protected List<XMLSoundTrack> soundtrack;

    /**
     * Gets the value of the soundtrack property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the soundtrack property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSoundtrack().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLSoundTrack }
     * 
     * 
     */
    public List<XMLSoundTrack> getSoundtrack() {
        if (soundtrack == null) {
            soundtrack = new ArrayList<XMLSoundTrack>();
        }
        return this.soundtrack;
    }

}
