//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.warheads;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InfDeathAnims.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InfDeathAnims">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="INSTANT"/>
 *     &lt;enumeration value="TWIRL"/>
 *     &lt;enumeration value="EXPLODE"/>
 *     &lt;enumeration value="FLY"/>
 *     &lt;enumeration value="BURN"/>
 *     &lt;enumeration value="ELECTRO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InfDeathAnims")
@XmlEnum
public enum XMLInfDeathAnims {

    INSTANT,
    TWIRL,
    EXPLODE,
    FLY,
    BURN,
    ELECTRO;

    public String value() {
        return name();
    }

    public static XMLInfDeathAnims fromValue(String v) {
        return valueOf(v);
    }

}
