//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.warheads;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import redhorizon.xml.XMLExtendableObject;


/**
 * <p>Java class for Warhead complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Warhead">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/common}ExtendableObject">
 *       &lt;sequence>
 *         &lt;element name="Effectiveness" type="{http://www.ultraq.net.nz/redhorizon/warheads}Effectiveness" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ImpactAnimation" type="{http://www.ultraq.net.nz/redhorizon/warheads}ImpactAnimation" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="InfDeathAnim" type="{http://www.ultraq.net.nz/redhorizon/warheads}InfDeathAnims" />
 *       &lt;attribute name="Spread" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeInt" />
 *       &lt;attribute name="Destroys">
 *         &lt;simpleType>
 *           &lt;list itemType="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Warhead", propOrder = {
    "effectiveness",
    "impactAnimation"
})
public class XMLWarhead
    extends XMLExtendableObject
{

    @XmlElement(name = "Effectiveness")
    protected List<XMLEffectiveness> effectiveness;
    @XmlElement(name = "ImpactAnimation")
    protected XMLImpactAnimation impactAnimation;
    @XmlAttribute(name = "InfDeathAnim")
    protected XMLInfDeathAnims infDeathAnim;
    @XmlAttribute(name = "Spread")
    protected Integer spread;
    @XmlAttribute(name = "Destroys")
    protected List<String> destroys;

    /**
     * Gets the value of the effectiveness property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the effectiveness property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEffectiveness().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLEffectiveness }
     * 
     * 
     */
    public List<XMLEffectiveness> getEffectiveness() {
        if (effectiveness == null) {
            effectiveness = new ArrayList<XMLEffectiveness>();
        }
        return this.effectiveness;
    }

    /**
     * Gets the value of the impactAnimation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLImpactAnimation }
     *     
     */
    public XMLImpactAnimation getImpactAnimation() {
        return impactAnimation;
    }

    /**
     * Sets the value of the impactAnimation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLImpactAnimation }
     *     
     */
    public void setImpactAnimation(XMLImpactAnimation value) {
        this.impactAnimation = value;
    }

    /**
     * Gets the value of the infDeathAnim property.
     * 
     * @return
     *     possible object is
     *     {@link XMLInfDeathAnims }
     *     
     */
    public XMLInfDeathAnims getInfDeathAnim() {
        return infDeathAnim;
    }

    /**
     * Sets the value of the infDeathAnim property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLInfDeathAnims }
     *     
     */
    public void setInfDeathAnim(XMLInfDeathAnims value) {
        this.infDeathAnim = value;
    }

    /**
     * Gets the value of the spread property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSpread() {
        return spread;
    }

    /**
     * Sets the value of the spread property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSpread(Integer value) {
        this.spread = value;
    }

    /**
     * Gets the value of the destroys property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the destroys property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestroys().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDestroys() {
        if (destroys == null) {
            destroys = new ArrayList<String>();
        }
        return this.destroys;
    }

}
