//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.factions;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the redhorizon.xml.factions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: redhorizon.xml.factions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLMultiplayerStats }
     * 
     */
    public XMLMultiplayerStats createXMLMultiplayerStats() {
        return new XMLMultiplayerStats();
    }

    /**
     * Create an instance of {@link XMLSubFaction }
     * 
     */
    public XMLSubFaction createXMLSubFaction() {
        return new XMLSubFaction();
    }

    /**
     * Create an instance of {@link XMLFaction }
     * 
     */
    public XMLFaction createXMLFaction() {
        return new XMLFaction();
    }

    /**
     * Create an instance of {@link XMLFactionData }
     * 
     */
    public XMLFactionData createXMLFactionData() {
        return new XMLFactionData();
    }

}
