//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ultraq.net.nz/redhorizon/factions", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package redhorizon.xml.factions;
