//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.factions;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import redhorizon.xml.XMLReferenceableObject;


/**
 * <p>Java class for AbstractFaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractFaction">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/common}ReferenceableObject">
 *       &lt;sequence>
 *         &lt;element name="Multiplayer" type="{http://www.ultraq.net.nz/redhorizon/factions}MultiplayerStats" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Playable">
 *         &lt;simpleType>
 *           &lt;list itemType="{http://www.ultraq.net.nz/redhorizon/factions}Playable" />
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractFaction", propOrder = {
    "multiplayer"
})
@XmlSeeAlso({
    XMLFaction.class,
    XMLSubFaction.class
})
public abstract class XMLAbstractFaction
    extends XMLReferenceableObject
{

    @XmlElement(name = "Multiplayer")
    protected XMLMultiplayerStats multiplayer;
    @XmlAttribute(name = "Playable")
    protected List<XMLPlayable> playable;

    /**
     * Gets the value of the multiplayer property.
     * 
     * @return
     *     possible object is
     *     {@link XMLMultiplayerStats }
     *     
     */
    public XMLMultiplayerStats getMultiplayer() {
        return multiplayer;
    }

    /**
     * Sets the value of the multiplayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLMultiplayerStats }
     *     
     */
    public void setMultiplayer(XMLMultiplayerStats value) {
        this.multiplayer = value;
    }

    /**
     * Gets the value of the playable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the playable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlayable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLPlayable }
     * 
     * 
     */
    public List<XMLPlayable> getPlayable() {
        if (playable == null) {
            playable = new ArrayList<XMLPlayable>();
        }
        return this.playable;
    }

}
