//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.factions;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import redhorizon.xml.media.XMLAnimation;


/**
 * <p>Java class for Faction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Faction">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/factions}AbstractFaction">
 *       &lt;sequence>
 *         &lt;element name="Radar" type="{http://www.ultraq.net.nz/redhorizon/media}Animation" minOccurs="0"/>
 *         &lt;element name="SubFaction" type="{http://www.ultraq.net.nz/redhorizon/factions}SubFaction" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Faction", propOrder = {
    "radar",
    "subFaction"
})
public class XMLFaction
    extends XMLAbstractFaction
{

    @XmlElement(name = "Radar")
    protected XMLAnimation radar;
    @XmlElement(name = "SubFaction", required = true)
    protected List<XMLSubFaction> subFaction;

    /**
     * Gets the value of the radar property.
     * 
     * @return
     *     possible object is
     *     {@link XMLAnimation }
     *     
     */
    public XMLAnimation getRadar() {
        return radar;
    }

    /**
     * Sets the value of the radar property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLAnimation }
     *     
     */
    public void setRadar(XMLAnimation value) {
        this.radar = value;
    }

    /**
     * Gets the value of the subFaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subFaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubFaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLSubFaction }
     * 
     * 
     */
    public List<XMLSubFaction> getSubFaction() {
        if (subFaction == null) {
            subFaction = new ArrayList<XMLSubFaction>();
        }
        return this.subFaction;
    }

}
