//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.factions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MultiplayerStats complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultiplayerStats">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="AirSpeed" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeFloat" default="1.0" />
 *       &lt;attribute name="Armour" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeFloat" default="1.0" />
 *       &lt;attribute name="BuildTime" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeFloat" default="1.0" />
 *       &lt;attribute name="Cost" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeFloat" default="1.0" />
 *       &lt;attribute name="Firepower" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeFloat" default="1.0" />
 *       &lt;attribute name="GroundSpeed" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeFloat" default="1.0" />
 *       &lt;attribute name="RateOfFire" type="{http://www.ultraq.net.nz/redhorizon/common}nonNegativeFloat" default="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiplayerStats")
public class XMLMultiplayerStats {

    @XmlAttribute(name = "AirSpeed")
    protected Float airSpeed;
    @XmlAttribute(name = "Armour")
    protected Float armour;
    @XmlAttribute(name = "BuildTime")
    protected Float buildTime;
    @XmlAttribute(name = "Cost")
    protected Float cost;
    @XmlAttribute(name = "Firepower")
    protected Float firepower;
    @XmlAttribute(name = "GroundSpeed")
    protected Float groundSpeed;
    @XmlAttribute(name = "RateOfFire")
    protected Float rateOfFire;

    /**
     * Gets the value of the airSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getAirSpeed() {
        if (airSpeed == null) {
            return  1.0F;
        } else {
            return airSpeed;
        }
    }

    /**
     * Sets the value of the airSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAirSpeed(Float value) {
        this.airSpeed = value;
    }

    /**
     * Gets the value of the armour property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getArmour() {
        if (armour == null) {
            return  1.0F;
        } else {
            return armour;
        }
    }

    /**
     * Sets the value of the armour property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setArmour(Float value) {
        this.armour = value;
    }

    /**
     * Gets the value of the buildTime property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getBuildTime() {
        if (buildTime == null) {
            return  1.0F;
        } else {
            return buildTime;
        }
    }

    /**
     * Sets the value of the buildTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBuildTime(Float value) {
        this.buildTime = value;
    }

    /**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getCost() {
        if (cost == null) {
            return  1.0F;
        } else {
            return cost;
        }
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCost(Float value) {
        this.cost = value;
    }

    /**
     * Gets the value of the firepower property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getFirepower() {
        if (firepower == null) {
            return  1.0F;
        } else {
            return firepower;
        }
    }

    /**
     * Sets the value of the firepower property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFirepower(Float value) {
        this.firepower = value;
    }

    /**
     * Gets the value of the groundSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getGroundSpeed() {
        if (groundSpeed == null) {
            return  1.0F;
        } else {
            return groundSpeed;
        }
    }

    /**
     * Sets the value of the groundSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setGroundSpeed(Float value) {
        this.groundSpeed = value;
    }

    /**
     * Gets the value of the rateOfFire property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getRateOfFire() {
        if (rateOfFire == null) {
            return  1.0F;
        } else {
            return rateOfFire;
        }
    }

    /**
     * Sets the value of the rateOfFire property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRateOfFire(Float value) {
        this.rateOfFire = value;
    }

}
