//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.factions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubFaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubFaction">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/factions}AbstractFaction">
 *       &lt;attribute name="Colour" use="required" type="{http://www.ultraq.net.nz/redhorizon/factions}SubFactionColour" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubFaction")
public class XMLSubFaction
    extends XMLAbstractFaction
{

    @XmlAttribute(name = "Colour", required = true)
    protected XMLSubFactionColour colour;

    /**
     * Gets the value of the colour property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSubFactionColour }
     *     
     */
    public XMLSubFactionColour getColour() {
        return colour;
    }

    /**
     * Sets the value of the colour property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSubFactionColour }
     *     
     */
    public void setColour(XMLSubFactionColour value) {
        this.colour = value;
    }

}
