/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nz_net_ultraq_redhorizon_filetypes_mix_MixFileKey */

#ifndef _Included_nz_net_ultraq_redhorizon_filetypes_mix_MixFileKey
#define _Included_nz_net_ultraq_redhorizon_filetypes_mix_MixFileKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nz_net_ultraq_redhorizon_filetypes_mix_MixFileKey
 * Method:    getBlowfishKeyNative
 * Signature: ([B[B[B[BI)V
 */
JNIEXPORT void JNICALL Java_nz_net_ultraq_redhorizon_filetypes_mix_MixFileKey_getBlowfishKeyNative
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
