/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class redhorizon_filetypes_mix_MixFileKey */

#ifndef _Included_redhorizon_filetypes_mix_MixFileKey
#define _Included_redhorizon_filetypes_mix_MixFileKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     redhorizon_filetypes_mix_MixFileKey
 * Method:    getBlowfishKey
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_redhorizon_filetypes_mix_MixFileKey_getBlowfishKey
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
