//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.media;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the redhorizon.xml.media package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: redhorizon.xml.media
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLSoundEffect }
     * 
     */
    public XMLSoundEffect createXMLSoundEffect() {
        return new XMLSoundEffect();
    }

    /**
     * Create an instance of {@link XMLSoundTrack }
     * 
     */
    public XMLSoundTrack createXMLSoundTrack() {
        return new XMLSoundTrack();
    }

    /**
     * Create an instance of {@link XMLMedia }
     * 
     */
    public XMLMedia createXMLMedia() {
        return new XMLMedia();
    }

    /**
     * Create an instance of {@link XMLImage }
     * 
     */
    public XMLImage createXMLImage() {
        return new XMLImage();
    }

    /**
     * Create an instance of {@link XMLAnimation }
     * 
     */
    public XMLAnimation createXMLAnimation() {
        return new XMLAnimation();
    }

}
