//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:54:28 PM NZST 
//


package redhorizon.xml.media;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Soundtrack complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Soundtrack">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ultraq.net.nz/redhorizon/media}Media">
 *       &lt;attribute name="TechLevel" use="required" type="{http://www.ultraq.net.nz/redhorizon/common}negativeOnePlusInt" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Soundtrack")
public class XMLSoundTrack
    extends XMLMedia
{

    @XmlAttribute(name = "TechLevel", required = true)
    protected int techLevel;

    /**
     * Gets the value of the techLevel property.
     * 
     */
    public int getTechLevel() {
        return techLevel;
    }

    /**
     * Sets the value of the techLevel property.
     * 
     */
    public void setTechLevel(int value) {
        this.techLevel = value;
    }

}
